import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { BrowserRouter, Routes, Route } from "react-router-dom";
import Index from "./pages/Index";
import About from "./pages/About";
import PrincipalMessage from "./pages/PrincipalMessage";
import VisionMission from "./pages/VisionMission";
import Faculty from "./pages/Faculty";
import Academics from "./pages/Academics";
import Admissions from "./pages/Admissions";
import Gallery from "./pages/Gallery";
import Events from "./pages/Events";
import News from "./pages/News";
import Contact from "./pages/Contact";
import Infrastructure from "./pages/Infrastructure";
import Curriculum from "./pages/Curriculum";
import Achievements from "./pages/Achievements";
import Sports from "./pages/Sports";
import CoCurricular from "./pages/CoCurricular";
import Transportation from "./pages/Transportation";
import FeeStructure from "./pages/FeeStructure";
import SchoolCalendar from "./pages/SchoolCalendar";
import StudentLife from "./pages/StudentLife";
import NotFound from "./pages/NotFound";
import ScrollToTop from "./components/ScrollToTop";
const queryClient = new QueryClient();
const App = () => (_jsx(QueryClientProvider, { client: queryClient, children: _jsxs(TooltipProvider, { children: [_jsx(Toaster, {}), _jsx(Sonner, {}), _jsxs(BrowserRouter, { children: [_jsx(ScrollToTop, {}), _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(Index, {}) }), _jsx(Route, { path: "/about", element: _jsx(About, {}) }), _jsx(Route, { path: "/principal-message", element: _jsx(PrincipalMessage, {}) }), _jsx(Route, { path: "/vision-mission", element: _jsx(VisionMission, {}) }), _jsx(Route, { path: "/faculty", element: _jsx(Faculty, {}) }), _jsx(Route, { path: "/academics", element: _jsx(Academics, {}) }), _jsx(Route, { path: "/admissions", element: _jsx(Admissions, {}) }), _jsx(Route, { path: "/gallery", element: _jsx(Gallery, {}) }), _jsx(Route, { path: "/events", element: _jsx(Events, {}) }), _jsx(Route, { path: "/news", element: _jsx(News, {}) }), _jsx(Route, { path: "/contact", element: _jsx(Contact, {}) }), _jsx(Route, { path: "/infrastructure", element: _jsx(Infrastructure, {}) }), _jsx(Route, { path: "/curriculum", element: _jsx(Curriculum, {}) }), _jsx(Route, { path: "/achievements", element: _jsx(Achievements, {}) }), _jsx(Route, { path: "/sports", element: _jsx(Sports, {}) }), _jsx(Route, { path: "/co-curricular", element: _jsx(CoCurricular, {}) }), _jsx(Route, { path: "/transportation", element: _jsx(Transportation, {}) }), _jsx(Route, { path: "/fee-structure", element: _jsx(FeeStructure, {}) }), _jsx(Route, { path: "/calendar", element: _jsx(SchoolCalendar, {}) }), _jsx(Route, { path: "/student-life", element: _jsx(StudentLife, {}) }), _jsx(Route, { path: "*", element: _jsx(NotFound, {}) })] })] })] }) }));
export default App;
