import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Layout from "@/components/Layout";
import PageHero from "@/components/PageHero";
import AnimatedSection from "@/components/AnimatedSection";
import { BookOpen, FlaskConical, Globe, Calculator, Palette, Code } from "lucide-react";
const subjects = [
    { icon: BookOpen, name: "Languages", desc: "English, Hindi, and Sanskrit with emphasis on communication skills." },
    { icon: Calculator, name: "Mathematics", desc: "Strong foundation in mathematical concepts and problem-solving." },
    { icon: FlaskConical, name: "Sciences", desc: "Physics, Chemistry, and Biology with hands-on lab experiences." },
    { icon: Globe, name: "Social Sciences", desc: "History, Geography, Civics, and Economics for global awareness." },
    { icon: Code, name: "Computer Science", desc: "Modern IT skills, programming, and digital literacy." },
    { icon: Palette, name: "Arts & Music", desc: "Creative expression through visual arts, music, and performing arts." },
];
const Academics = () => (_jsxs(Layout, { children: [_jsx(PageHero, { title: "Academics", subtitle: "Comprehensive education for holistic development", breadcrumb: "Academics" }), _jsx("section", { className: "section-padding", children: _jsxs("div", { className: "container mx-auto", children: [_jsx(AnimatedSection, { children: _jsxs("div", { className: "text-center mb-12", children: [_jsx("h2", { className: "section-title", children: "Academic Programs" }), _jsx("div", { className: "gold-underline" }), _jsx("p", { className: "section-subtitle", children: "We offer a robust academic program from Pre-Primary to Senior Secondary, aligned with CBSE standards." })] }) }), _jsx("div", { className: "grid md:grid-cols-3 gap-8 mb-16", children: ["Pre-Primary (Nursery–KG)", "Primary (Classes I–V)", "Secondary (Classes VI–X)", "Senior Secondary (Classes XI–XII)"].map((level, i) => (_jsx(AnimatedSection, { delay: i * 0.1, children: _jsxs("div", { className: "bg-card rounded-xl border border-border p-6 card-hover", children: [_jsx("div", { className: "w-10 h-10 bg-secondary/20 rounded-lg flex items-center justify-center mb-3", children: _jsx("span", { className: "font-heading font-bold text-secondary", children: i + 1 }) }), _jsx("h3", { className: "font-heading font-semibold text-lg mb-2", children: level }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Age-appropriate curriculum designed for comprehensive learning and development." })] }) }, level))) }), _jsx(AnimatedSection, { children: _jsxs("div", { className: "text-center mb-8", children: [_jsx("h2", { className: "section-title", children: "Subjects Offered" }), _jsx("div", { className: "gold-underline" })] }) }), _jsx("div", { className: "grid sm:grid-cols-2 lg:grid-cols-3 gap-6", children: subjects.map((s, i) => (_jsx(AnimatedSection, { delay: i * 0.08, children: _jsxs("div", { className: "bg-cream rounded-xl p-6 card-hover", children: [_jsx(s.icon, { className: "w-8 h-8 text-primary mb-3" }), _jsx("h3", { className: "font-heading font-semibold text-foreground mb-2", children: s.name }), _jsx("p", { className: "text-sm text-muted-foreground", children: s.desc })] }) }, s.name))) })] }) })] }));
export default Academics;
