import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Layout from "@/components/Layout";
import PageHero from "@/components/PageHero";
import AnimatedSection from "@/components/AnimatedSection";
import { Link } from "react-router-dom";
import { ClipboardList, FileText, UserCheck, CreditCard, ArrowRight, CheckCircle } from "lucide-react";
const steps = [
    { icon: ClipboardList, title: "Enquiry", desc: "Visit the school or fill out the online enquiry form to begin the process." },
    { icon: FileText, title: "Application", desc: "Submit the completed application form along with required documents." },
    { icon: UserCheck, title: "Assessment", desc: "Students appear for an age-appropriate assessment/interaction." },
    { icon: CreditCard, title: "Enrollment", desc: "Upon selection, complete the admission formalities and fee payment." },
];
const docs = ["Birth Certificate", "Previous School Transfer Certificate", "Report Card of Last Class", "Passport Size Photographs (4)", "Aadhar Card Copy", "Parent's ID Proof"];
const Admissions = () => (_jsxs(Layout, { children: [_jsx(PageHero, { title: "Admissions", subtitle: "Join the St. Joseph's family \u2013 Admissions Open!", breadcrumb: "Admissions" }), _jsx("section", { className: "section-padding", children: _jsxs("div", { className: "container mx-auto", children: [_jsx(AnimatedSection, { children: _jsxs("div", { className: "text-center mb-12", children: [_jsx("h2", { className: "section-title", children: "Admission Process" }), _jsx("div", { className: "gold-underline" }), _jsx("p", { className: "section-subtitle", children: "A simple four-step process to begin your child's journey with us." })] }) }), _jsx("div", { className: "grid sm:grid-cols-2 lg:grid-cols-4 gap-6 mb-16", children: steps.map((s, i) => (_jsx(AnimatedSection, { delay: i * 0.1, children: _jsxs("div", { className: "bg-card rounded-xl border border-border p-6 text-center card-hover relative", children: [_jsx("div", { className: "w-12 h-12 bg-primary rounded-full flex items-center justify-center mx-auto mb-4 text-primary-foreground font-heading font-bold", children: i + 1 }), _jsx(s.icon, { className: "w-8 h-8 text-secondary mx-auto mb-3" }), _jsx("h3", { className: "font-heading font-semibold mb-2", children: s.title }), _jsx("p", { className: "text-sm text-muted-foreground", children: s.desc })] }) }, s.title))) }), _jsxs("div", { className: "grid md:grid-cols-2 gap-10", children: [_jsx(AnimatedSection, { children: _jsxs("div", { className: "bg-cream rounded-2xl p-8", children: [_jsx("h3", { className: "font-heading font-bold text-xl text-primary mb-4", children: "Required Documents" }), _jsx("ul", { className: "space-y-3", children: docs.map((d) => (_jsxs("li", { className: "flex items-center gap-3 text-muted-foreground", children: [_jsx(CheckCircle, { className: "w-5 h-5 text-secondary shrink-0" }), " ", d] }, d))) })] }) }), _jsx(AnimatedSection, { delay: 0.15, children: _jsxs("div", { className: "bg-primary rounded-2xl p-8 text-primary-foreground", children: [_jsx("h3", { className: "font-heading font-bold text-xl text-secondary mb-4", children: "Admissions Open 2026-27" }), _jsx("p", { className: "text-primary-foreground/80 mb-6", children: "We are now accepting applications for the upcoming academic session. Limited seats available for all classes." }), _jsxs(Link, { to: "/contact", className: "btn-secondary inline-flex items-center gap-2", children: ["Enquire Now ", _jsx(ArrowRight, { className: "w-4 h-4" })] })] }) })] })] }) })] }));
export default Admissions;
