import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Layout from "@/components/Layout";
import PageHero from "@/components/PageHero";
import AnimatedSection from "@/components/AnimatedSection";
import { IndianRupee, Info } from "lucide-react";
const feeData = [
    { class: "Nursery – UKG", admission: "15,000", tuition: "2,500/month", annual: "5,000" },
    { class: "Class I – V", admission: "18,000", tuition: "3,000/month", annual: "6,000" },
    { class: "Class VI – VIII", admission: "20,000", tuition: "3,500/month", annual: "7,000" },
    { class: "Class IX – X", admission: "22,000", tuition: "4,000/month", annual: "8,000" },
    { class: "Class XI – XII", admission: "25,000", tuition: "4,500/month", annual: "9,000" },
];
const FeeStructure = () => (_jsxs(Layout, { children: [_jsx(PageHero, { title: "Fee Structure", subtitle: "Transparent and affordable education", breadcrumb: "Fee Structure" }), _jsx("section", { className: "section-padding", children: _jsxs("div", { className: "container mx-auto max-w-4xl", children: [_jsx(AnimatedSection, { children: _jsx("div", { className: "bg-card rounded-2xl border border-border overflow-hidden shadow-lg", children: _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full", children: [_jsx("thead", { children: _jsxs("tr", { className: "bg-primary text-primary-foreground", children: [_jsx("th", { className: "text-left p-4 font-heading", children: "Class" }), _jsx("th", { className: "text-left p-4 font-heading", children: "Admission Fee" }), _jsx("th", { className: "text-left p-4 font-heading", children: "Tuition Fee" }), _jsx("th", { className: "text-left p-4 font-heading", children: "Annual Charges" })] }) }), _jsx("tbody", { children: feeData.map((f, i) => (_jsxs("tr", { className: `border-t border-border ${i % 2 === 0 ? "bg-card" : "bg-muted/30"}`, children: [_jsx("td", { className: "p-4 font-semibold text-foreground", children: f.class }), _jsxs("td", { className: "p-4 text-sm text-muted-foreground flex items-center gap-1", children: [_jsx(IndianRupee, { className: "w-3 h-3" }), f.admission] }), _jsxs("td", { className: "p-4 text-sm text-muted-foreground", children: ["\u20B9", f.tuition] }), _jsxs("td", { className: "p-4 text-sm text-muted-foreground", children: ["\u20B9", f.annual] })] }, f.class))) })] }) }) }) }), _jsx(AnimatedSection, { delay: 0.2, children: _jsxs("div", { className: "bg-cream rounded-xl p-6 mt-8 flex items-start gap-3", children: [_jsx(Info, { className: "w-5 h-5 text-secondary shrink-0 mt-0.5" }), _jsxs("div", { className: "text-sm text-muted-foreground space-y-1", children: [_jsx("p", { children: "* Fee structure is indicative and subject to revision. Please contact the school office for exact details." }), _jsx("p", { children: "* Transportation and hostel fees are separate and depend on the distance/facility availed." }), _jsx("p", { children: "* Scholarships available for meritorious and economically weaker students." })] })] }) })] }) })] }));
export default FeeStructure;
