import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Layout from "@/components/Layout";
import PageHero from "@/components/PageHero";
import AnimatedSection from "@/components/AnimatedSection";
import { Eye, Target, Compass, Lightbulb } from "lucide-react";
const VisionMission = () => (_jsxs(Layout, { children: [_jsx(PageHero, { title: "Vision & Mission", subtitle: "Our guiding principles for educational excellence", breadcrumb: "Vision & Mission" }), _jsx("section", { className: "section-padding", children: _jsxs("div", { className: "container mx-auto max-w-5xl", children: [_jsxs("div", { className: "grid md:grid-cols-2 gap-10", children: [_jsx(AnimatedSection, { children: _jsxs("div", { className: "bg-card rounded-2xl p-8 border border-border h-full card-hover", children: [_jsx("div", { className: "w-16 h-16 bg-primary/10 rounded-2xl flex items-center justify-center mb-6", children: _jsx(Eye, { className: "w-8 h-8 text-primary" }) }), _jsx("h2", { className: "font-heading font-bold text-2xl text-primary mb-4", children: "Our Vision" }), _jsx("p", { className: "text-muted-foreground leading-relaxed", children: "To be a premier educational institution that nurtures young minds to become compassionate, innovative, and responsible global citizens, rooted in values and committed to excellence in all endeavors." })] }) }), _jsx(AnimatedSection, { delay: 0.15, children: _jsxs("div", { className: "bg-card rounded-2xl p-8 border border-border h-full card-hover", children: [_jsx("div", { className: "w-16 h-16 bg-secondary/10 rounded-2xl flex items-center justify-center mb-6", children: _jsx(Target, { className: "w-8 h-8 text-secondary" }) }), _jsx("h2", { className: "font-heading font-bold text-2xl text-primary mb-4", children: "Our Mission" }), _jsx("p", { className: "text-muted-foreground leading-relaxed", children: "To provide holistic education that develops intellectual curiosity, physical fitness, spiritual growth, and emotional resilience. We aim to create a learning environment that inspires creativity, critical thinking, and lifelong learning." })] }) })] }), _jsx("div", { className: "grid md:grid-cols-2 gap-10 mt-10", children: [
                            { icon: Compass, title: "Our Philosophy", desc: "Education at St. Joseph's is guided by the belief that every child is unique and possesses inherent potential. We provide personalized attention and diverse opportunities for students to discover and develop their talents." },
                            { icon: Lightbulb, title: "Our Approach", desc: "We adopt a learner-centered approach that combines traditional values with modern pedagogy. Through experiential learning, technology integration, and collaborative projects, we make education engaging and meaningful." },
                        ].map((item, i) => (_jsx(AnimatedSection, { delay: 0.3 + i * 0.15, children: _jsxs("div", { className: "bg-cream rounded-2xl p-8 h-full", children: [_jsx(item.icon, { className: "w-10 h-10 text-secondary mb-4" }), _jsx("h3", { className: "font-heading font-bold text-xl text-primary mb-3", children: item.title }), _jsx("p", { className: "text-muted-foreground leading-relaxed", children: item.desc })] }) }, item.title))) })] }) })] }));
export default VisionMission;
